version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-nosql-projeto
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./setup_mongodb.js:/setup_mongodb.js
      - ./consultas_mongodb.js:/consultas_mongodb.js
      - ./solucao_nosql.md:/solucao_nosql.md

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

volumes:
  mongodb_data: